---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
```{r}
library(tidyverse)
library(lattice)
```


## Loading and preprocessing the data
```{r, echo=TRUE}
unzip("activity.zip", junkpaths = TRUE)
activityData <- read.csv("activity.csv")

activityData$date <- as.Date(activityData$date)

head(activityData)

```



## What is mean total number of steps taken per day?
```{r}
# Calculate the total number of steps taken per day
totalSteps <- activityData %>%
    group_by(date) %>%
    summarise(total = sum(steps, na.rm = TRUE))
# Histogram of the total number of steps taken each day
hist(totalSteps$total)
```
```{r}
# Mean & Median of the total number of steps taken per day
meanSteps <- mean(totalSteps$total, na.rm = TRUE)
medianSteps <- median(totalSteps$total, na.rm = TRUE)

meanSteps
medianSteps
```



## What is the average daily activity pattern?
```{r}
avgDailyActivity <- activityData %>%
    group_by(interval) %>%
    summarize(average_steps = mean(steps, na.rm = TRUE))

with(avgDailyActivity, plot(x = interval, y = average_steps, type = "l",
                                xlab = "5 min Intervals in a day",
                                ylab = "Average Number of Steps", 
                                main = "The Average Daily Activity Pattern"))
```

```{r}
# 5-minute interval which contains maximum average number of steps
maxInterval = avgDailyActivity$interval[which.max(avgDailyActivity$average_steps)]
maxInterval
```

## Imputing missing values

```{r}
# Calculate the missing values in the dataset
sum(is.na(activityData))
```

```{r}

activityData_new <- merge(avgDailyActivity, activityData, by = "interval")
naSteps <- is.na(activityData_new$steps)
activityData_new$steps[naSteps] <- activityData_new$average_steps[naSteps]
activityData_new <- activityData_new[,-(2)]

```

```{r}
totalStepsNew <- activityData_new %>%
    group_by(date) %>%
    summarise(total_steps = sum(steps))
# Histogram of the total number of steps taken each day
with(totalStepsNew, hist(total_steps))
```


```{r}
mean_totalStepsNew <- mean(totalStepsNew$total_steps)
median_totalStepsNew <- median(totalStepsNew$total_steps)

mean_totalStepsNew
median_totalStepsNew
```


```{r}

```

## Are there differences in activity patterns between weekdays and weekends?


```{r}
# Creating a new factor variable with two levels - weekday and weekend
activityData_new$day <- "weekday"
activityData_new$day[weekdays(as.Date(activityData_new$date), abb=TRUE) %in% c("Sat","Sun")] <- "weekend"

activityData_new$day <- as.factor(activityData_new$day)
```


```{r}
# Make a time series panel plot of the 5-minute interval and the average number of steps taken on weekday and weekend
avgDailyActivity_new <- aggregate(steps ~ interval + day, data = activityData_new, FUN="mean")

```


```{r}
xyplot(steps ~ interval | day, data = avgDailyActivity_new,
       type = "l", layout = c(1,2),
       main = "Average  5-min. activity intervals: Weekdays vs. Weekends",
       xlab = "5-min Interval",
       ylab = "Average Steps")

```

